clamav: fixup improper quoting
Commit 217e06badb146539122732ab0eb27fd17cce09e5 [clamav: fix gcc 6.x
build failure.] fixed a typo in "PACKAGECONFIG" (was missing the 'G')
but unfortunately the PACKAGECONFIG string was incorrectly formed due
to mismatched quotes. This caused a parsing error:

  ERROR: Unable to parse .../meta-security/recipes-security/clamav/clamav_0.99.2.bb
  ...

Removed the unneeded quotes to fix the parsing issue.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>