libewf: fix build issue
ERROR: gettext-native required but not in DEPENDS for file /build/build_artifacts/master/tmp-glibc/work/i586-oe-linux/libewf/20140608-r0/libewf-20140608/configure.ac.
Missing inherit gettext?

Signed-off-by: Armin Kuster <akuster808@gmail.com>